// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJ9Hj9hXYTu9ZkdnNwO-P-R0PXl7yTzM',
    appId: '1:507847211522:web:6db102c98ef07c325e851b',
    messagingSenderId: '507847211522',
    projectId: 'medshipapp',
    authDomain: 'medshipapp.firebaseapp.com',
    storageBucket: 'medshipapp.firebasestorage.app',
    measurementId: 'G-VSVKQXQNTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjUirtmt4vu0lSUO8Xig-tgdYHYHB_Zok',
    appId: '1:507847211522:android:59a5600834c352925e851b',
    messagingSenderId: '507847211522',
    projectId: 'medshipapp',
    storageBucket: 'medshipapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdr9ollC3e8V4WtUZfZamOEKe_kXms4DE',
    appId: '1:507847211522:ios:ad47ee67c0ccf3185e851b',
    messagingSenderId: '507847211522',
    projectId: 'medshipapp',
    storageBucket: 'medshipapp.firebasestorage.app',
    iosBundleId: 'com.example.medship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWJ9Hj9hXYTu9ZkdnNwO-P-R0PXl7yTzM',
    appId: '1:507847211522:web:43f7886a8f3a5beb5e851b',
    messagingSenderId: '507847211522',
    projectId: 'medshipapp',
    authDomain: 'medshipapp.firebaseapp.com',
    storageBucket: 'medshipapp.firebasestorage.app',
    measurementId: 'G-XDXPECQV5Q',
  );
}
